# Generated by Django 5.1 on 2024-09-02 12:13

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor.fields.RichTextField(blank=True, max_length=200, verbose_name='Біографія')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Місце проживання')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('profession', models.CharField(blank=True, max_length=30, verbose_name='Професія')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
