# Generated by Django 5.1 on 2024-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='category',
            field=models.CharField(choices=[('education', 'Освіта'), ('leisure', 'Дозвілля'), ('entertainment', 'Розваги'), ('other', 'Інше')], default='other', max_length=50),
        ),
    ]
