# Generated by Django 5.1 on 2024-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='likes',
        ),
        migrations.AddField(
            model_name='addition',
            name='favorites',
            field=models.IntegerField(blank=True, default=0, verbose_name='Улюблене'),
        ),
    ]
