# Generated by Django 5.1 on 2024-08-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0002_addition_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='favorites',
        ),
    ]
