# Generated by Django 5.1 on 2024-08-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='views',
        ),
    ]
