# Generated by Django 5.1 on 2024-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0009_remove_comment_likes_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
