# Generated by Django 5.1 on 2024-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='category',
        ),
        migrations.AddField(
            model_name='addition',
            name='categories',
            field=models.ManyToManyField(blank=True, to='additions.category', verbose_name='Категорії'),
        ),
    ]
