# Generated by Django 5.1 on 2024-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0012_remove_addition_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addition',
            name='categories',
        ),
        migrations.AddField(
            model_name='addition',
            name='categories',
            field=models.ManyToManyField(blank=True, to='additions.category'),
        ),
    ]
