# Generated by Django 5.1 on 2024-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0013_category_remove_addition_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='categories',
        ),
        migrations.AddField(
            model_name='addition',
            name='categories',
            field=models.CharField(blank=True, choices=[('education', 'Освіта'), ('leisure', 'Дозвілля'), ('entertainment', 'Розваги'), ('other', 'Інше')], max_length=255, verbose_name='Категорії'),
        ),
    ]
