# Generated by Django 5.1 on 2024-08-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0014_remove_addition_categories_addition_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='addition',
            name='categories',
        ),
        migrations.AddField(
            model_name='addition',
            name='category',
            field=models.CharField(choices=[('education', 'Освіта'), ('leisure', 'Дозвілля'), ('entertainment', 'Розваги'), ('other', 'Інше')], default='other', max_length=50),
        ),
    ]
