# Generated by Django 5.1 on 2024-09-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0015_delete_category_remove_addition_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='media/post_images/', verbose_name='Мініатюра'),
        ),
        migrations.AlterField(
            model_name='addition',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
