# Generated by Django 5.1 on 2024-09-02 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additions', '0016_addition_image_thumbnail_alter_addition_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
    ]
